---
# server_ip: "{{ hostvars[groups['prod'] | difference(groups['client']) | first]['ansible_default_ipv4']['address'] }}"
server_ip: "10.10.10.110"
client_ip: "10.10.10.111"
ansible_user: "debian"

# ssl
ssl_remote_tls_dir: "/opt/vault/tls"
ssl_remote_ca_trust_store_dir: "/usr/share/ca-certificates/vault"
ssl_ca_chain_name: "ca"
ssl_remote_user: vault
ssl_remote_cert_name: "vault"
ssl_remote_cert_common_name: "vault"
ssl_remote_cert_san:
  - "DNS:vault.service.consul"

# vault
vault_config_dir: "/etc/vault.d"
vault_data_dir: "/opt/vault/data"
vault_tls_dir: "/opt/vault/tls"
vault_ca_cert_dir: "{{ ssl_remote_ca_trust_store_dir }}"
vault_store_bw: false
vault_server_fqdn: "{{ server_ip }}"
vault_terraform_workspace: "default"
vault_admin_password: "password"
vault_kvuser_password: "password"

# consul-template
consul_template_config_dir: "/etc/consul-template"
vault_agent_token_file_path: "{{ vault_data_dir }}/.vault-token"

# consul
consul_config_dir: "/etc/consul.d"
consul_data_dir: "/opt/consul"
consul_tls_dir: "{{ consul_data_dir }}/tls"
consul_server_ip: "{{ server_ip }}"
consul_ttl: "168h"
consul_upstream_dns_address: ["192.168.86.49", "1.1.1.1"]
setup_consul_watches: false

# nomad
nomad_config_dir: "/etc/nomad.d"
nomad_data_dir: "/opt/nomad/data"
nomad_tls_dir: "/opt/nomad/data/tls"
nomad_server_ip: "{{ server_ip }}"
nomad_ttl: "168h"
