port:
  # nomad ui
  tcp6:4646:
    listening: true
  # consul https ui
  tcp6:8501:
    listening: true
  # consul dns
  tcp6:8600:
    listening: true

service:
  nomad:
    enabled: true
    running: true
  consul:
    enabled: true
    running: true
  consul-template:
    enabled: true
    running: true

gossfile:
  base.yml: {}
