---
- import_tasks: install_webhook.yml

- name: Create hooks directory
  file:
    path: "{{ webhook_hooks_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy webhook.service
  template:
    src: "webhook.service.j2"
    dest: "/etc/systemd/system/webhook.service"
    owner: root
    group: root
    mode: 0644
  notify: restart webhook

- name: Copy hooks file
  template:
    src: "hooks.yml.j2"
    dest: "{{ webhook_hooks_dir }}/hooks.yml"
    owner: root
    group: root
    mode: 0644
  notify: reload webhook

- name: Start and enable webhook
  systemd:
    name: webhook
    state: started
    enabled: true

- name: Proxy webhook behind nginx
  import_tasks: nginx.yml
  when: webhook_nginx_setup
