---
all:
  children:
    cluster:
      children:
        server:
          hosts:
            10.10.10.110:
            10.10.10.130:
        client:
          hosts:
            10.10.10.111:
            10.10.10.131:
        prod:
          hosts:
            10.10.10.110:
            10.10.10.111:
        dev:
          hosts:
            10.10.10.130:
            10.10.10.131:
    nas:
      hosts:
        10.10.10.102:
      vars:
        ansible_user: debian
    template:
      hosts:
        10.10.10.250:
