---
common_user: debian
common_timezone: "Asia/Singapore"
common_keyring_dir: "/etc/apt/keyrings"
common_nfs_dir: "/mnt/storage"
common_packages:
  - sudo
  - curl
  - git
  - openssh-server
  - vim
  - make
  - gnupg
  - nfs-common
  - software-properties-common
  - jq
  - unzip
  - ca-certificates
  - qemu-guest-agent
common_dotfiles: []
  # - url: https://raw.githubusercontent.com/foo/repo/master/vimrc
  #   dest: /home/{{ common_user }}/.vimrc

common_nomad_version: "1.6.1-1"
common_consul_version: "1.15.4-1"
common_vault_version: "1.14.0-1"
common_consul_template_version: "0.32.0-1"
common_reset_nomad: true
