---
- hosts: all
  become: true
  vars:
    user: debian

  roles:
    - role: common
      vars:
        common_user: "{{ user }}"
        common_reset_nomad: true
        common_dotfiles_url: https://github.com/kencx/dotfiles.git

    - name: Install Docker
      role: geerlingguy.docker
      vars:
        # install docker compose plugin instead of docker-compose binary
        docker_install_compose_plugin: true
        docker_install_compose: false
        docker_users: ["{{ user }}"]

    - name: Security hardening
      role: kencx.ansible_collection.security
      vars:
        ssh_disable_root_login: true
        ufw_rules:
          - {rule: 'allow', port: '22', proto: 'tcp', comment: 'ssh'}
          - {rule: 'allow', port: '4646', proto: 'tcp', comment: 'nomad HTTP'}
          - {rule: 'allow', port: '4647', proto: 'tcp', comment: 'nomad RPC'}
          - {rule: 'allow', port: '4648', proto: 'tcp', comment: 'nomad Serf WAN'}  # server only
          - {rule: 'allow', port: '4648', proto: 'udp', comment: 'nomad Serf WAN'}  # server only
          - {rule: 'allow', port: '8200', proto: 'tcp', comment: 'vault UI'}
          - {rule: 'allow', port: '8300', proto: 'tcp', comment: 'consul RPC'}      # server only
          - {rule: 'allow', port: '8301', proto: 'tcp', comment: 'consul Serf LAN'}
          - {rule: 'allow', port: '8301', proto: 'udp', comment: 'consul Serf LAN'}
          - {rule: 'allow', port: '8302', proto: 'tcp', comment: 'consul Serf WAN'}
          - {rule: 'allow', port: '8302', proto: 'udp', comment: 'consul Serf WAN'}
          - {rule: 'allow', port: '8501', proto: 'tcp', comment: 'consul HTTPS'}
          - {rule: 'allow', port: '8503', proto: 'tcp', comment: 'consul gRPC'}
          - {rule: 'allow', port: '8600', proto: 'tcp', comment: 'consul DNS'}
          - {rule: 'allow', port: '8600', proto: 'udp', comment: 'consul DNS'}

    - name: Goss validation
      role: kencx.ansible_collection.goss
      vars:
        goss_dir: "../goss"
        goss_file: "base.yml"
